# Generated by Django 3.2.6 on 2021-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=64, unique=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
    ]
