# Generated by Django 3.2.6 on 2021-08-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
