# Generated by Django 3.2.6 on 2022-03-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0005_imagemodel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='literature.imagemodel'),
        ),
    ]
