# Generated by Django 3.2.6 on 2022-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0007_auto_20220330_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to='uploads/', verbose_name='Зображення'),
        ),
    ]
