# Generated by Django 3.2.6 on 2022-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0009_auto_20220514_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='images',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/', verbose_name='Зображення'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
