# Generated by Django 3.2.6 on 2022-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0010_auto_20220514_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='links',
        ),
        migrations.AddField(
            model_name='place',
            name='links',
            field=models.TextField(blank=True, verbose_name='Посилання'),
        ),
        migrations.DeleteModel(
            name='LinklModel',
        ),
    ]
