# Generated by Django 3.2.6 on 2022-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0011_auto_20220514_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x',
            field=models.IntegerField(default=0, verbose_name='Координата Х'),
        ),
        migrations.AddField(
            model_name='place',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Координата У'),
        ),
    ]
