# Generated by Django 3.2.6 on 2022-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0012_auto_20220514_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='x',
            field=models.FloatField(default=0, verbose_name='Координата Х'),
        ),
        migrations.AlterField(
            model_name='place',
            name='y',
            field=models.FloatField(default=0, verbose_name='Координата У'),
        ),
    ]
